# Site settings
title:          yoonyoung's blog
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://yooonyoung.github.io/"

# Author
author:
  name:         yoonyoung
  url:          https://chester.how
  email:        dbsydd@gmail.com

# Build settings
markdown:       kramdown

disqus-shortname: yooonyoung

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
